### ISSUE TITLE
Implement Auth middleware 

### ISSUE THREAD

**Issue by vsilent** [trydirect/stacker#3]
Implement Auth middleware
Input: Bearer Token

**Comment by smart--petea** [comment]
The OAuth should support the following actions:
1. add a client. A new pair client_id and client_secret are generated. client_id is a unique 32 hex string. client_secret is generated by a cryptographical library, transformed in hex. the length is 256 bits.
2. delete the application. All active tokens should be revoked.
3. reset the secret. Active access tokens remains active. The use of refresh tokens can be continued only after the secrets are updated.
4. authorization callback url

**Comment by smart--petea** [comment]
Next improvments are required:
1. the user should be allowed no moret than a number of clients. The number of clients at moment is a general setting saved in configuration.yaml
2. the client secret should be unique acrros client.secret column
3. the update client endpoint should be added. it acts the same as a reset endpoint. each calls ends with a new generated secret. the update endpoint can't update the clients with null secret.
4. the  disable client endpoint should be added. by disabling I mean the secret is set in null.
5. the client bearer should forbid any actions with null client secret
6. the enable client endpoint should be added. It acts as update endpoint, regardless of secret nullness. I mean it generates a non null secret.
7. the client common logic should be moved into helpers.
